# Generated by Django 3.0.2 on 2020-01-19 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Kategoria',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kategoria',
                'verbose_name_plural': 'Kategorie',
            },
        ),
        migrations.CreateModel(
            name='Producent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producent',
                'verbose_name_plural': 'Producenci',
            },
        ),
        migrations.CreateModel(
            name='Produkty',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=60)),
                ('opis', models.TextField(blank=True)),
                ('cena', models.DecimalField(decimal_places=2, max_digits=99999)),
                ('obraz', models.FileField(blank=True, upload_to='')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('stan', models.IntegerField(default=0)),
                ('numer', models.IntegerField(blank=True, default=876543, null=True)),
                ('slug', models.SlugField()),
                ('regał', models.CharField(blank=True, choices=[('Regał_1', 'Regał 1'), ('Regał_2', 'Regał 2'), ('Regał_3', 'Regał 3'), ('Regał_4', 'Regał 4')], default='Regał_1', max_length=30)),
                ('półka', models.CharField(choices=[('Półka_1', 'Półka 1'), ('Półka_2', 'Półka 2'), ('Półka_3', 'Półka 3'), ('Półka_4', 'Półka 4')], default='Półka_3', max_length=30)),
                ('lokacja_x', models.CharField(blank=True, choices=[('slot_1', 'Slot 1'), ('slot_2', 'Slot 2'), ('slot_3', 'Slot 3'), ('slot_4', 'Slot 4'), ('slot_5', 'Slot 5'), ('slot_6', 'Slot 6'), ('slot_7', 'Slot 7'), ('slot_8', 'Slot 8')], default='slot_1', max_length=30)),
                ('kategoria', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.Kategoria')),
                ('producent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='produkty.Producent')),
            ],
            options={
                'verbose_name': 'Produkt',
                'verbose_name_plural': 'Produkty',
            },
        ),
    ]
