# Generated by Django 3.0.2 on 2020-01-19 06:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='slug',
        ),
    ]
