# Generated by Django 2.2 on 2019-11-15 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0018_auto_20190501_0727'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='stan',
            field=models.IntegerField(default=0),
        ),
    ]
