# Generated by Django 2.2 on 2019-11-15 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0019_produkty_stan'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='numer',
            field=models.IntegerField(default=235120, max_length=6),
        ),
    ]
