# Generated by Django 2.2 on 2019-11-15 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0020_produkty_numer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
