# Generated by Django 2.2.7 on 2019-11-30 09:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0021_delete_comment'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='kategoria',
            options={'verbose_name': 'Kategoria', 'verbose_name_plural': 'Kategorie'},
        ),
    ]
