# Generated by Django 2.2.7 on 2019-11-30 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0022_auto_20191130_1004'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='slug',
            field=models.SlugField(default=0),
            preserve_default=False,
        ),
    ]
