# Generated by Django 3.0.2 on 2020-01-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0023_produkty_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='lokalizacja',
            field=models.IntegerField(default=0, max_length=6),
        ),
    ]
