# Generated by Django 3.0.2 on 2020-01-14 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0024_produkty_lokalizacja'),
    ]

    operations = [
        migrations.AddField(
            model_name='produkty',
            name='półka',
            field=models.CharField(blank=True, choices=[('Regał_1', 'Regał 1'), ('Regał_2', 'Regał 2'), ('Regał_3', 'Regał 3'), ('Regał', 'Regał'), ('4', '4')], default='NOWE', max_length=30),
        ),
    ]
