# Generated by Django 3.0.2 on 2020-01-14 05:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0025_produkty_półka'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='półka',
            field=models.CharField(blank=True, choices=[('Regał_1', 'Regał 1'), ('Regał_2', 'Regał 2'), ('Regał_3', 'Regał 3'), ('Regał_4', 'Regał 4')], default='NOWE', max_length=30),
        ),
    ]
