# Generated by Django 3.0.2 on 2020-01-14 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0027_auto_20200114_0649'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='lokacja_x',
            field=models.CharField(blank=True, choices=[('slot_1', 'Slot 1'), ('slot_2', 'Slot 2'), ('slot_3', 'Slot 3'), ('slot_4', 'Slot 4'), ('slot_5', 'Slot 5'), ('slot_6', 'Slot 6'), ('slot_7', 'Slot 7'), ('slot_8', 'Slot 8')], default='slot_1', max_length=30),
        ),
    ]
