# Generated by Django 3.0.2 on 2020-01-15 07:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0028_auto_20200114_0651'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='produkty',
            name='tagi',
        ),
        migrations.DeleteModel(
            name='Tagi',
        ),
    ]
