# Generated by Django 3.0.2 on 2020-01-15 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('produkty', '0029_auto_20200115_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='produkty',
            name='półka',
            field=models.CharField(choices=[('Półka_1', 'Półka 1'), ('Półka_2', 'Półka 2'), ('Półka_3', 'Półka 3'), ('Półka_4', 'Półka 4')], default='Półka_3', max_length=30),
        ),
    ]
