# Generated by Django 3.0.2 on 2020-01-19 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('produkty', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('status', models.CharField(blank=0, choices=[('NOWE', 'Nowe'), ('ZAPISANE', 'Zapisane'), ('WYSŁANE', 'Wysłane'), ('GOTOWE', 'Gotowe'), ('BRAK_MOŻLIWOŚCI_REALIZACJI', 'Brak Możliwości Realizacji'), ('ZREALIZOWANE', 'Zrealizowane'), ('ARCHIWALNE', 'Archiwalne')], default='NOWE', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('products', models.ManyToManyField(blank=True, to='produkty.Produkty')),
            ],
            options={
                'verbose_name': 'Zamówienie',
                'verbose_name_plural': 'Zamówienia',
            },
        ),
    ]
