# Generated by Django 3.0.2 on 2020-01-11 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0002_auto_20200110_1742'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('ZAPISENE', 'Zapisene'), ('WYSŁANE', 'Wysłane'), ('ZREALIZOWANE', 'Zrealizowane'), ('ARCHIWALNE', 'Archiwalne')], max_length=15),
        ),
    ]
