# Generated by Django 3.0.2 on 2020-01-11 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0003_cart_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('NOWE', 'Nowe'), ('ZAPISENE', 'Zapisene'), ('WYSŁANE', 'Wysłane'), ('ZREALIZOWANE', 'Zrealizowane'), ('ARCHIWALNE', 'Archiwalne')], default='NOWE', max_length=15),
        ),
    ]
