# Generated by Django 3.0.2 on 2020-01-11 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0004_auto_20200111_0818'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=True, choices=[('NOWE', 'Nowe'), ('ZAPISEAE', 'Zapiseae'), ('WYSŁANE', 'Wysłane'), ('GOTOWE', 'Gotowe'), ('ZREALIZOWANE', 'Zrealizowane'), ('ARCHIWALNE', 'Archiwalne')], default='NOWE', max_length=15),
        ),
    ]
