# Generated by Django 3.0.2 on 2020-01-18 05:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('koszyk', '0006_auto_20200112_1021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='status',
            field=models.CharField(blank=0, choices=[('NOWE', 'Nowe'), ('ZAPISANE', 'Zapisane'), ('WYSŁANE', 'Wysłane'), ('GOTOWE', 'Gotowe'), ('BRAK_MOŻLIWOŚCI_REALIZACJI', 'Brak Możliwości Realizacji'), ('ZREALIZOWANE', 'Zrealizowane'), ('ARCHIWALNE', 'Archiwalne')], default='NOWE', max_length=30),
        ),
    ]
